export const taskPlanningStyle=`
.entry-form .task-carry{display:flex;align-items:center;gap:10px}.entry-form .task-carry input{width:18px;height:18px;flex:none}
.task-month-grid .task-month-day{height:60px}.task-month-day .task-done-count{color:#65cba0}.task-month-day[aria-pressed=true] .task-done-count{color:inherit}.task-completed-row .row-sub{color:var(--muted)}
.task-month-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:4px;width:100%}.task-month-grid>strong{text-align:center;font-size:11px;color:var(--muted);padding:6px 0}.task-month-day{height:48px;min-width:0;padding:4px 0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;border:1px solid var(--line);border-radius:5px;background:var(--panel);color:var(--text);font-size:14px}.task-month-day small{font-size:10px;line-height:12px;color:var(--muted);min-height:12px}.task-month-day.is-today{border-color:var(--text)}.task-month-day[aria-pressed=true]{background:var(--text);color:var(--panel)}.task-month-day[aria-pressed=true] small{color:inherit}.task-day-agenda{margin-top:18px;min-width:0}.task-day-agenda h3{font-size:16px;margin:0 0 10px}.task-day-agenda .daily-task-row>div{min-width:0}.task-day-agenda .daily-task-row button{overflow-wrap:anywhere}.task-day-agenda .row-sub{overflow-wrap:anywhere}
.task-planning-grid{display:grid;gap:12px;overflow:auto}.task-planning-grid.kanban{grid-template-columns:repeat(5,minmax(210px,1fr))}.task-planning-grid.calendar{grid-template-columns:repeat(7,minmax(130px,1fr))}.task-planning-grid>section{min-width:0;border-top:2px solid var(--line);padding:8px}.task-planning-grid h3{font-size:13px}.task-planning-grid .daily-task-row{font-size:12px}.task-tools{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.task-tools input,.task-tools select{max-width:100%;min-width:0;background:var(--panel);color:var(--text);padding:10px;border:1px solid var(--line);border-radius:5px}.task-sync{font-size:11px;color:var(--muted)}.task-weekdays{display:flex;gap:10px;flex-wrap:wrap}.task-weekdays label{display:flex;gap:4px;align-items:center}.entry-form .task-weekdays input{width:18px;height:18px}
`;
export const taskPlanningScript=String.raw`
let taskQuery='',taskList='',taskLayout='list',taskMonth=data?.date?.slice(0,7)||new Date().toISOString().slice(0,7);
let taskSelectedDate=data?.date||new Date().toISOString().slice(0,10);
function taskCalendar(items,keys){
 if(!keys.includes(taskSelectedDate))taskSelectedDate=keys.includes(data.date)?data.date:keys[0];
 const byDay=new Map(keys.map(k=>[k,items.filter(t=>taskOccurrenceDates(t,k,k).length>0).sort((a,b)=>(a.startTime||'99:99').localeCompare(b.startTime||'99:99')||a.name.localeCompare(b.name))]));
 const selected=byDay.get(taskSelectedDate)||[];
 const completed=new Map(keys.map(k=>[k,[]]));
 for(const t of dailyTasks){
  if(t.deleted||(!t.done&&!t.repeat)||(taskList&&t.list!==taskList)||(taskQuery&&!(t.name+' '+(t.description||'')+' '+(t.tags||[]).join(' ')).toLowerCase().includes(taskQuery.toLowerCase())))continue;
  // Recurring tasks retain completed occurrences while the current task advances.
  const history=t.history?.length?(t.repeat?t.history:t.history.slice(-1)):t.done?[{date:t.date,name:t.name,startTime:t.startTime,endTime:t.endTime}]:[];
  const seen=new Set();
  for(const h of history){const key=h.id||h.date;if(seen.has(key))continue;seen.add(key);completed.get(h.date)?.push({task:t,entry:h});}
 }
 const finished=completed.get(taskSelectedDate)||[];
 const doneRows=finished.map(({task:t,entry:h})=>'<div class="daily-task-row task-completed-row">'+icons.check+'<div><button data-id="'+E(t.id)+'" onclick="editDailyTask(this.dataset.id)">'+E(h.name)+'</button><div class="row-sub">Выполнено'+(h.startTime?' · '+E(h.startTime)+(h.endTime?'–'+E(h.endTime):''):'')+'</div></div></div>').join('');
 return '<div class="task-month-grid" aria-label="Дни месяца">'+['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(d=>'<strong>'+d+'</strong>').join('')+'<div aria-hidden="true"></div>'.repeat((new Date(taskMonth+'-01T12:00:00Z').getUTCDay()+6)%7)+keys.map(k=>{const count=byDay.get(k).length,done=completed.get(k).length;return '<button class="task-month-day '+(k===data.date?'is-today':'')+'" data-date="'+k+'" data-count="'+count+'" data-done="'+done+'" aria-label="'+k+', осталось: '+count+', выполнено: '+done+'" aria-pressed="'+(k===taskSelectedDate)+'" onclick="taskSelectedDate=this.dataset.date;render()"><span>'+Number(k.slice(8))+'</span><small>'+(count?count+' зад.':'')+'</small><small class="task-done-count">'+(done?done+' вып.':'')+'</small></button>'}).join('')+'</div><section class="task-day-agenda"><h3>'+E(new Date(taskSelectedDate+'T12:00:00').toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'}))+' · '+selected.length+' зад.'+(finished.length?' · '+finished.length+' вып.':'')+'</h3>'+(selected.map(t=>taskRow(t,taskSelectedDate)).join('')+doneRows||empty('Нет заданий на этот день'))+'</section>';
}
const taskLabels={planned:'Запланировано',active:'В работе',waiting:'Ожидает',completed:'Выполнено',cancelled:'Отменено'};
const taskCacheKey=tg?.initDataUnsafe?.user?.id?'fl-tasks-'+tg.initDataUnsafe.user.id:null;
let taskQueue=[],taskConflicts={};
try{const saved=taskCacheKey?JSON.parse(localStorage.getItem(taskCacheKey)||'{}'):{};taskQueue=saved.queue||[];dailyTasks=saved.tasks||dailyTasks;taskConflicts=saved.conflicts||{}}catch{}
function persistTasks(){if(taskCacheKey)localStorage.setItem(taskCacheKey,JSON.stringify({queue:taskQueue,tasks:dailyTasks,conflicts:taskConflicts}))}
const taskApiBase=api;
api=async function(path,options={}){if(path!=='tasks'||options.method!=='POST')return taskApiBase(path,options);const body=JSON.parse(options.body);if(!body.task)return taskApiBase(path,options);try{return await taskApiBase(path,options)}catch(e){if(e.message==='task_conflict'){const remote=(await taskApiBase('tasks')).tasks.find(t=>t.id===body.task.id);taskConflicts[body.task.id]={local:body.task,remote};persistTasks();throw e}if(e instanceof TypeError){if(!taskQueue.some(p=>p.requestId===body.requestId))taskQueue.push(body);dailyTasks=[...(dailyTasks||[]).filter(t=>t.id!==body.task.id),body.task];persistTasks();return {ok:true,queued:true}}throw e}};
loadDailyTasks=async function(){try{
 while(taskQueue.length){const op=taskQueue[0];try{const r=await taskApiBase('tasks',{method:'POST',body:JSON.stringify(op)});taskQueue.shift();const next=taskQueue.find(p=>p.task.id===op.task.id);if(next&&r.task)next.task.revision=r.task.revision;persistTasks()}catch(e){if(e.message==='task_conflict'){const remote=(await taskApiBase('tasks')).tasks.find(t=>t.id===op.task.id);taskConflicts[op.task.id]={local:op.task,remote};persistTasks()}break}}
 dailyTasks=(await taskApiBase('tasks')).tasks.filter(t=>!t.deleted);
 for(const op of taskQueue)dailyTasks=[...dailyTasks.filter(t=>t.id!==op.task.id),op.task];persistTasks();
 }catch(e){if(!dailyTasks)alertError(e)}if(currentTab==='tasks')render()};
window.addEventListener('online',()=>loadDailyTasks());
function taskRow(t,occurrenceDate=t.date){const state=taskConflicts[t.id]?'Конфликт':taskQueue.some(p=>p.task.id===t.id)?'Ожидает отправки':'Сохранено';return '<div class="daily-task-row"><input type="checkbox" aria-label="Выполнено" '+(t.done?'checked':'')+(t.repeat&&taskLayout==='calendar'&&occurrenceDate!==data.date?' disabled':'')+' data-id="'+E(t.id)+'" onchange="toggleDailyTask(this)"><div><button data-id="'+E(t.id)+'" onclick="editDailyTask(this.dataset.id)">'+E(t.name)+'</button><div class="row-sub">'+((taskIsMissed(t,data.date)||taskLayout==='calendar'&&!t.done&&!taskCarriesOver(t)&&occurrenceDate<data.date)?'Не выполнено · ':'')+E(occurrenceDate||'Без даты')+(t.startTime?' · '+E(t.startTime)+(t.endTime?'–'+E(t.endTime):''):'')+(t.deadline?' · Срок: '+E(t.deadline):'')+'</div><div class="row-sub">'+E([t.list,...t.tags||[]].filter(Boolean).join(' · '))+'</div><button class="task-sync" data-id="'+E(t.id)+'" onclick="resolveTaskConflict(this.dataset.id)">'+state+'</button></div></div>'}
view_tasks=function(){if(!dailyTasks)return empty('Загрузка заданий');const items=dailyTasks.filter(t=>taskMatches(t,taskLayout==='calendar'?'all':dailyFilter,data.date,taskQuery,taskList)&&(taskLayout!=='calendar'||taskOccurrenceDates(t,taskMonth+'-01',taskMonth+'-31').length>0)).sort((a,b)=>(a.order||0)-(b.order||0)||a.date.localeCompare(b.date));
 const tools='<div class="task-tools"><input type="search" aria-label="Поиск" placeholder="Поиск и теги" value="'+E(taskQuery)+'" onchange="taskQuery=this.value;render()"><select aria-label="Период" onchange="dailyFilter=this.value;render()">'+[['inbox','Входящие'],['today','Сегодня'],['upcoming','Предстоящие'],['overdue','Просроченные'],['missed','Не выполнено'],['undated','Без даты'],['done','Выполненные'],['all','Все']].map(([v,n])=>'<option value="'+v+'" '+(v===dailyFilter?'selected':'')+'>'+n+'</option>').join('')+'</select><select aria-label="Список" onchange="taskList=this.value;render()"><option value="">Все списки</option>'+[...new Set(dailyTasks.map(t=>t.list).filter(Boolean))].map(n=>'<option '+(n===taskList?'selected':'')+'>'+E(n)+'</option>').join('')+'</select><select aria-label="Представление" onchange="taskLayout=this.value;render()">'+[['list','Список'],['kanban','Канбан'],['calendar','Календарь']].map(([v,n])=>'<option value="'+v+'" '+(v===taskLayout?'selected':'')+'>'+n+'</option>').join('')+'</select>'+(taskLayout==='calendar'?'<input type="month" aria-label="Месяц" value="'+taskMonth+'" onchange="taskMonth=this.value;render()">':'')+'<button class="icon-btn" title="Добавить задание" aria-label="Добавить задание" onclick="editDailyTask()">'+icons.plus+'</button></div>';
 if(taskLayout==='list')return tools+(items.map(t=>taskRow(t)).join('')||empty('Нет заданий'));
 const keys=taskLayout==='kanban'?Object.keys(taskLabels):Array.from({length:new Date(Number(taskMonth.slice(0,4)),Number(taskMonth.slice(5)),0).getDate()},(_,i)=>taskMonth+'-'+String(i+1).padStart(2,'0'));
 if(taskLayout==='calendar')return tools+taskCalendar(items,keys);
 return tools+'<div class="task-planning-grid '+taskLayout+'">'+(taskLayout==='calendar'?['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(d=>'<strong>'+d+'</strong>').join('')+'<div></div>'.repeat((new Date(taskMonth+'-01T12:00:00Z').getUTCDay()+6)%7):'')+keys.map(k=>'<section><h3>'+E(taskLayout==='kanban'?taskLabels[k]:k.slice(8))+'</h3>'+items.filter(t=>taskLayout==='kanban'?(t.done?'completed':t.status||'planned')===k:taskOccurrenceDates(t,k,k).length>0).map(t=>taskRow(t,taskLayout==='calendar'?k:t.date)).join('')+'</section>').join('')+'</div>'};
const planningEditor=editDailyTask;
editDailyTask=function(id){planningEditor(id);const f=document.getElementById('daily-form'),t=f.task;
 f.elements.date.required=false;if(!id){f.elements.date.value='';f.task.date=''}
 const extra=document.createElement('div');extra.className='entry-form';extra.id='task-extra';
 extra.innerHTML='<div class="entry-pair">'+entryField('extraStart','Время начала','time')+entryField('extraEnd','Время окончания','time')+'</div>'+entryField('extraDescription','Описание','text')+entryField('extraList','Список','text')+entryField('extraTags','Теги через запятую','text')+entryField('extraLinks','Ссылки и заметки (через запятую)','text')+entryField('extraMedia','Произведение: путь заметки','text')+entryField('extraProject','Проект: ID','text')+entrySelect('extraStatus','Статус',Object.entries(taskLabels))+entrySelect('extraRepeat','Повторение',[['','Не повторять'],['daily','Ежедневно'],['weekdays','По дням недели'],['monthly','Ежемесячно'],['after','После выполнения']])+entryField('extraInterval','Интервал после выполнения, дней','number','min="1" max="365"')+entryField('extraDay','Число месяца','number','min="1" max="31"')+'<div class="task-weekdays">'+['Вс','Пн','Вт','Ср','Чт','Пт','Сб'].map((d,i)=>'<label><input type="checkbox" data-weekday="'+i+'" '+(t.repeat?.weekdays?.includes(i)?'checked':'')+'>'+d+'</label>').join('')+'</div>'+entryField('extraReminder','Напомнить в Telegram','time')+entryField('extraOrder','Порядок в списке','number');
 f.insertBefore(extra,f.querySelector('[type=submit]'));
 f.task={...f.task};
 const carry=document.createElement('label');carry.className='task-carry';
 carry.innerHTML='<input type="checkbox" name="extraCarry">Переносить, если не выполнено';
 extra.prepend(carry);const carryInput=f.elements.extraCarry;carryInput.checked=taskCarriesOver(t);
 carryInput.onchange=()=>{f.task.carryOver=carryInput.checked;};
 const values={extraStart:t.startTime||'',extraEnd:t.endTime||'',extraDescription:t.description||'',extraList:t.list||'',extraTags:(t.tags||[]).join(', '),extraLinks:(t.links||[]).join(', '),extraMedia:t.mediaPath||'',extraProject:t.projectId||'',extraStatus:t.done?'completed':t.status||'planned',extraRepeat:t.repeat?.kind||'',extraInterval:t.repeat?.interval||1,extraDay:t.repeat?.day||1,extraReminder:t.reminderTime||'',extraOrder:t.order||0};for(const[k,v]of Object.entries(values))f.elements[k].value=v;
 const repeatFields=()=>{const k=f.elements.extraRepeat.value;if(f.task.carryOver===undefined)carryInput.checked=taskCarriesOver({...t,repeat:k?{kind:k}:null});f.elements.extraInterval.parentElement.style.display=k==='after'?'':'none';f.elements.extraDay.parentElement.style.display=k==='monthly'?'':'none';extra.querySelector('.task-weekdays').style.display=k==='weekdays'?'':'none'};f.elements.extraRepeat.onchange=repeatFields;repeatFields();
 const description=document.createElement('textarea');description.name='extraDescription';description.rows=4;description.value=t.description||'';f.elements.extraDescription.replaceWith(description);
 const replaceChoice=(name,choices)=>{if(!f.isConnected)return;const input=f.elements[name],select=document.createElement('select');select.name=name;select.innerHTML='<option value="">Не связано</option>'+choices.map(([v,n])=>'<option value="'+E(v)+'">'+E(n)+'</option>').join('');if(input.value&&!choices.some(([v])=>v===input.value))select.insertAdjacentHTML('beforeend','<option value="'+E(input.value)+'">'+E(input.value)+'</option>');select.value=input.value;input.replaceWith(select)};
 replaceChoice('extraMedia',[...new Map([...data.current,...data.library].filter(m=>m.path).map(m=>[m.path,[m.path,m.title]])).values()]);
 api('projects').then(b=>replaceChoice('extraProject',b.scopes.map(s=>[s.id,s.name]))).catch(()=>{});
 const addSub=f.querySelector('button[onclick*="daily-subs"]');if(addSub)addSub.onclick=()=>{const holder=document.getElementById('daily-subs');holder.insertAdjacentHTML('beforeend',subtaskRow());const d=document.createElement('input');d.type='date';d.ariaLabel='Дата подзадачи';holder.lastElementChild.append(d)};
 for(const [i,row]of [...document.querySelectorAll('#daily-subs .subtask-edit')].entries()){const d=document.createElement('input');d.type='date';d.ariaLabel='Дата подзадачи';d.value=t.subtasks[i]?.date||'';row.append(d)}
 if(t.history?.length)extra.insertAdjacentHTML('beforeend','<h3>История выполнения</h3>'+t.history.slice().reverse().map(h=>'<div class="row-sub">'+E(h.date)+(h.startTime?' '+E(h.startTime)+(h.endTime?'–'+E(h.endTime):''):'')+' · '+E(h.name)+'</div>').join(''));
};
saveDailyForm=async function(f){if(f.busy||!f.reportValidity())return;const st=f.elements.extraStart.value,et=f.elements.extraEnd.value;if(et&&(!st||et<=st)){document.getElementById('daily-error').textContent='Окончание должно быть позже начала (в пределах одного дня).';return;}f.busy=true;const v=n=>f.elements[n].value,split=v=>[...new Set(v.split(',').map(s=>s.trim()).filter(Boolean))];const status=v('extraStatus');const task={...f.task,name:v('name'),date:v('date'),deadline:v('deadline'),priority:v('priority'),habitName:v('habitName'),description:v('extraDescription'),list:v('extraList'),tags:split(v('extraTags')),links:split(v('extraLinks')),mediaPath:v('extraMedia'),projectId:v('extraProject'),status,done:status==='completed',reminderTime:v('extraReminder'),startTime:v('extraStart'),endTime:v('extraEnd'),order:Number(v('extraOrder'))||0,repeat:v('extraRepeat')?{kind:v('extraRepeat'),interval:Number(v('extraInterval')),day:Number(v('extraDay')),weekdays:[...f.querySelectorAll('[data-weekday]:checked')].map(e=>Number(e.dataset.weekday))}:null,subtasks:[...document.querySelectorAll('#daily-subs .subtask-edit')].map(el=>({text:el.querySelector('[type=text]').value.trim(),checked:el.querySelector('[type=checkbox]').checked,date:el.querySelector('[type=date]')?.value||''}))};try{await api('tasks',{method:'POST',body:JSON.stringify({task,requestId:f.requestId})});closeModal();await loadDailyTasks()}catch(e){document.getElementById('daily-error').textContent=e.message;if(e.message==='task_conflict')resolveTaskConflict(task.id)}finally{f.busy=false}};
function resolveTaskConflict(id){const conflict=taskConflicts[id];if(!conflict?.remote)return;const merged={...conflict.local},keys=[...new Set([...Object.keys(conflict.local),...Object.keys(conflict.remote)])].filter(k=>!['id','revision'].includes(k)&&JSON.stringify(conflict.local[k])!==JSON.stringify(conflict.remote[k]));modal('<h3>Сравнить версии</h3><form id="task-conflict" class="entry-form">'+keys.map((k,i)=>'<label>'+E(k)+'<div class="row-sub">Локально: '+E(JSON.stringify(conflict.local[k])||'—')+'<br>Облако: '+E(JSON.stringify(conflict.remote[k])||'—')+'</div><select data-key="'+E(k)+'"><option value="local">Локальная версия</option><option value="remote">Облачная версия</option></select></label>').join('')+'<button type="submit" class="primary">Объединить выбранное</button><button type="button" class="secondary" id="task-use-remote">Принять облачную версию</button></form>');document.getElementById('task-use-remote').onclick=async()=>{taskQueue=taskQueue.filter(p=>p.task.id!==id);delete taskConflicts[id];persistTasks();closeModal();await loadDailyTasks()};document.getElementById('task-conflict').onsubmit=async e=>{e.preventDefault();for(const el of e.target.querySelectorAll('[data-key]'))merged[el.dataset.key]=(el.value==='remote'?conflict.remote:conflict.local)[el.dataset.key];try{await taskApiBase('tasks',{method:'POST',body:JSON.stringify({task:{...merged,revision:conflict.remote.revision},confirm:merged.deleted,requestId:crypto.randomUUID()})});taskQueue=taskQueue.filter(p=>p.task.id!==id);delete taskConflicts[id];persistTasks();closeModal();await loadDailyTasks()}catch(error){alertError(error)}}}
let taskDeepLink=new URLSearchParams(location.search).get('task');const taskPlanningLoad=load;load=async function(){await taskPlanningLoad();if(taskDeepLink&&data){const id=taskDeepLink;taskDeepLink=null;await loadDailyTasks();currentTab='tasks';render();if(dailyTasks?.some(t=>t.id===id))editDailyTask(id)}};
`;
