export const dailyTaskStyle=`.nav{grid-template-columns:repeat(6,minmax(0,1fr))}.nav button{min-width:0;font-size:10px}.daily-task-row{display:grid;grid-template-columns:26px minmax(0,1fr);gap:12px;padding:16px 0;border-bottom:1px solid var(--line)}.daily-task-row input{width:20px;height:20px}.daily-task-row button{border:0;background:none;text-align:left;padding:0;overflow-wrap:anywhere}`;
export const dailyTaskScript=String.raw`
let dailyTasks=null,dailyFilter='today';
async function loadDailyTasks(){try{dailyTasks=(await api('tasks')).tasks.filter(t=>!t.deleted);if(currentTab==='tasks')render()}catch(e){alertError(e)}}
function view_tasks(){if(!dailyTasks)return empty('Загрузка заданий');const today=data.date;const items=dailyTasks.filter(t=>dailyFilter==='all'||dailyFilter==='done'?dailyFilter==='all'||t.done:!t.done&&(dailyFilter==='today'?t.date===today:dailyFilter==='upcoming'?t.date>today:(t.deadline||t.date)<today)).sort((a,b)=>a.date.localeCompare(b.date));return '<div class="board-toolbar"><select aria-label="Период" onchange="dailyFilter=this.value;render()">'+[['today','Сегодня'],['upcoming','Предстоящие'],['overdue','Просроченные'],['done','Выполненные'],['all','Все']].map(([v,n])=>'<option value="'+v+'" '+(v===dailyFilter?'selected':'')+'>'+n+'</option>').join('')+'</select><button class="icon-btn" title="Добавить задание" aria-label="Добавить задание" onclick="editDailyTask()">'+icons.plus+'</button></div>'+ (items.map(t=>'<div class="daily-task-row"><input type="checkbox" aria-label="Выполнено" '+(t.done?'checked':'')+' data-id="'+E(t.id)+'" onchange="toggleDailyTask(this)"><div><button data-id="'+E(t.id)+'" onclick="editDailyTask(this.dataset.id)">'+E(t.name)+'</button><div class="row-sub">'+E(t.date)+(t.deadline?' · Срок: '+E(t.deadline):'')+(t.subtasks.length?' · '+t.subtasks.filter(s=>s.checked).length+'/'+t.subtasks.length:'')+'</div></div></div>').join('')||empty('Нет заданий'))}
function editDailyTask(id){const task=dailyTasks?.find(t=>t.id===id)||{id:crypto.randomUUID(),name:'',date:data.date,deadline:'',priority:'',habitName:'',done:false,deleted:false,revision:0,subtasks:[]};modal('<h3>Задание</h3><form id="daily-form" class="entry-form" onsubmit="event.preventDefault();saveDailyForm(this)">'+entryField('name','Название','text','required maxlength="250"')+'<div class="entry-pair">'+entryField('date','Плановая дата','date','required')+entryField('deadline','Дедлайн','date')+'</div>'+entrySelect('priority','Приоритет',[['','Без приоритета'],['low','Низкий'],['medium','Средний'],['high','Высокий']])+entrySelect('habitName','Привычка',[['','Без привычки'],...data.habits.filter(h=>h.type==='timer').map(h=>[h.name,h.name])])+'<div id="daily-subs">'+task.subtasks.map(subtaskRow).join('')+'</div><button type="button" class="secondary" onclick="document.getElementById(\'daily-subs\').insertAdjacentHTML(\'beforeend\',subtaskRow())">'+icons.plus+'Подзадача</button><div class="entry-error" role="alert" id="daily-error"></div><button class="primary" type="submit">Сохранить</button>'+(id?'<button class="secondary danger" type="button" onclick="deleteDailyTask()">Удалить</button>':'')+'</form>');const f=document.getElementById('daily-form');f.task=task;f.requestId=crypto.randomUUID();for(const k of ['name','date','deadline','priority','habitName'])f.elements[k].value=task[k]}
async function saveDailyForm(f){if(f.busy||!f.reportValidity())return;f.busy=true;const task={...f.task,...Object.fromEntries(new FormData(f)),subtasks:[...document.querySelectorAll('#daily-subs .subtask-edit')].map(el=>({text:el.querySelector('[type=text]').value.trim(),checked:el.querySelector('[type=checkbox]').checked}))};try{await api('tasks',{method:'POST',body:JSON.stringify({task,requestId:f.requestId})});closeModal();await loadDailyTasks()}catch(e){document.getElementById('daily-error').textContent=e.message==='task_conflict'?'Задание изменилось. Закройте редактор и обновите список.':e.message}finally{f.busy=false}}
async function toggleDailyTask(el){el.disabled=true;const task=dailyTasks.find(t=>t.id===el.dataset.id);try{await api('tasks',{method:'POST',body:JSON.stringify({task:{...task,done:el.checked},requestId:crypto.randomUUID()})})}catch(e){alertError(e)}await loadDailyTasks()}
function deleteDailyTask(){const task=document.getElementById('daily-form').task;modal('<h3>Удалить задание?</h3><p>'+E(task.name)+'</p><button class="secondary" onclick="closeModal()">Отмена</button><button id="daily-delete" class="secondary danger">Удалить</button>');document.getElementById('daily-delete').onclick=async function(){this.disabled=true;try{await api('tasks',{method:'POST',body:JSON.stringify({task:{...task,deleted:true},confirm:true,requestId:crypto.randomUUID()})});closeModal();await loadDailyTasks()}catch(e){this.disabled=false;alertError(e)}}}
const dailyBaseTab=tab;tab=function(name){dailyBaseTab(name);if(name==='tasks')loadDailyTasks()};
const dailyBaseRender=render;render=function(){dailyBaseRender();if(currentTab==='tasks')document.getElementById('heading').textContent='Задания'};
const dailyEditor=editDailyTask;editDailyTask=function(id){dailyEditor(id);if(!id)return;const task=dailyTasks.find(t=>t.id===id);if(task.done)return;const button=document.createElement('button');button.type='button';button.className='secondary';button.innerHTML=icons.play+'Начать сессию';button.onclick=async()=>{button.disabled=true;try{await api('tasks',{method:'POST',body:JSON.stringify({action:'start',id})});closeModal();currentTab='timer';timerPanel='timer';await load()}catch(e){button.disabled=false;alertError(e)}};document.getElementById('daily-form').append(button)};
document.querySelector('.nav').insertAdjacentHTML('beforeend','<button data-tab="tasks" onclick="tab(this.dataset.tab)">'+icons.check+'Задания</button>');
`;
