import { webAppStyle } from './webapp-style';
import { House, Timer, Library, ChartNoAxesCombined, RefreshCw, Play, Pause, Check, X, Search, BookOpen, ArrowUpRight, Flame, Layers, LockKeyhole, Plus, NotebookPen, Columns3, Trash2, History } from 'lucide-static';
import {sessionStyle,sessionScript} from './webapp-sessions-ui';
import { projectStyle, projectScript } from './webapp-projects-ui';
import { dailyTaskStyle, dailyTaskScript } from './webapp-tasks-ui';
import { taskPlanningStyle, taskPlanningScript } from './webapp-task-planning';
import { occurrenceDates,shiftDate,taskCarriesOver,taskIsOverdue,taskIsMissed,taskMatches } from '../../src/tasks/planning';
import { creationScript, creationStyle } from './webapp-create-ui';

const icons = Object.fromEntries(Object.entries({ home: House, timer: Timer, library: Library,
  stats: ChartNoAxesCombined, refresh: RefreshCw, play: Play, pause: Pause, check: Check,
  close: X, search: Search, book: BookOpen, arrow: ArrowUpRight, streak: Flame, layers: Layers, lock: LockKeyhole, plus: Plus, capture: NotebookPen, kanban: Columns3, trash: Trash2, history: History
}).map(([key, svg]) => [key, svg.replace('<svg', '<svg aria-hidden="true"').replace(/class="[^"]*"/, 'class="icon"')]));

export function webAppHtml(): string {
  return `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#111515"><title>Focus Library</title>
<script src="https://telegram.org/js/telegram-web-app.js?63"></script>
<style>
${webAppStyle}
${creationStyle}
${projectStyle}
${sessionStyle}
${dailyTaskStyle}
${taskPlanningStyle}
</style></head><body><main class="app"><header class="top"><div class="brand">${icons.layers} Focus Library</div><div class="eyebrow" id="date">Личное пространство</div><div class="title-row"><h1 id="heading">Сегодня</h1><button class="icon-btn" onclick="load()" aria-label="Обновить" title="Обновить">${icons.refresh}</button></div></header><div id="content"><div class="loading">Загрузка данных…</div></div></main>
<nav class="nav" aria-label="Разделы"><button class="active" data-tab="today" onclick="tab('today')">${icons.home}Сегодня</button><button data-tab="timer" onclick="tab('timer')">${icons.timer}Таймер</button><button data-tab="library" onclick="tab('library')">${icons.library}Библиотека</button><button data-tab="stats" onclick="tab('stats')">${icons.stats}Статистика</button></nav><div id="overlay"></div>
<script>
const icons=${JSON.stringify(icons)};
const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();tg?.setHeaderColor('#111515');tg?.setBackgroundColor('#111515');
let data=null,currentTab='today',ticker=null,filters={q:'',collection:''};
const init=tg?.initData||'';const E=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,options={}){const r=await fetch('/app/api/'+path,{...options,headers:{'Authorization':'tma '+init,'Content-Type':'application/json',...(options.headers||{})}});const j=await r.json();if(!r.ok)throw new Error(j.error||'request_failed');return j}
async function load(){try{data=await api('state?q='+encodeURIComponent(filters.q)+'&collection='+encodeURIComponent(filters.collection));document.getElementById('date').textContent=new Date(data.date+'T12:00:00').toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'});render()}catch(e){document.getElementById('content').innerHTML='<div class="error">'+icons.lock+'<div>Ваше личное пространство</div><small>'+E(e.message==='unauthorized'?'Откройте приложение из чата с ботом в Telegram.':'Не удалось загрузить данные. Попробуйте ещё раз.')+'</small><button class="secondary" onclick="load()">'+icons.refresh+'Повторить</button></div>'}}
function tab(name){currentTab=name;render();window.scrollTo(0,0)}
function render(){if(!data)return;clearInterval(ticker);document.querySelectorAll('.nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===currentTab);b.setAttribute('aria-current',b.dataset.tab===currentTab?'page':'false')});const names={today:'Сегодня',timer:'Время для себя',library:'Библиотека',stats:'Ваш ритм'};document.getElementById('heading').textContent=names[currentTab];document.getElementById('content').innerHTML=window['view_'+currentTab]();if(data.timer&&data.timer.timer_state==='running'){const initial=data.timer.elapsed,started=Date.now();ticker=setInterval(()=>{data.timer.elapsed=initial+Math.floor((Date.now()-started)/1000);document.querySelectorAll('.timer-clock').forEach(el=>el.textContent=clock(data.timer.elapsed))},1000)}}
function progress(v,g){return Math.min(100,g?Math.round(v/g*100):0)}function clock(v){v=Math.max(0,Math.floor(v));return [Math.floor(v/3600),Math.floor(v%3600/60),v%60].map(x=>String(x).padStart(2,'0')).join(':')}
function view_today(){const done=data.habits.filter(h=>['completed','partial'].includes(h.today.state)).length;return '<section class="summary"><div class="metric"><b>'+done+'/'+data.habits.length+'</b><span>привычек</span></div><div class="metric"><b>'+data.goals.filter(g=>g.value>=g.goal).length+'/'+data.goals.length+'</b><span>дневных норм</span></div><div class="metric"><b>'+data.tasks.length+'</b><span>задач</span></div></section>'+activeTimer()+section('Дневные нормы',data.goals.length,goals())+section('Привычки',data.habits.length,habits())+section('Сейчас в процессе',data.current.length,mediaGrid(data.current))+section('Задачи',data.tasks.length,tasks())}
function activeTimer(){if(!data.timer)return'';return '<section class="section"><button class="active-session" data-go="timer" onclick="tab(this.dataset.go)">'+icons.timer+'<div><div class="eyebrow"><span class="live-dot"></span>'+(data.timer.timer_state==='running'?'Сессия идёт':'На паузе')+'</div><div class="row-title">'+E(data.timer.habit_name)+'</div><div class="timer-clock">'+clock(data.timer.elapsed)+'</div></div>'+icons.arrow+'</button></section>'}
function section(title,count,body){return '<section class="section"><div class="section-head"><h2>'+title+'</h2><span class="count">'+count+'</span></div>'+body+'</section>'}
function goals(){return data.goals.length?'<div class="goal-grid">'+data.goals.map(g=>'<div class="goal"><div class="goal-top">'+icons.book+E(labelCollection(g.collection))+'</div><strong>'+g.value+' <span>/ '+g.goal+'</span></strong><small>'+E(unit(g.unit))+' сегодня</small><div class="bar"><i style="width:'+progress(g.value,g.goal)+'%"></i></div></div>').join('')+'</div>':empty('Дневные нормы отключены')}
function habits(){return data.habits.length?'<div class="list">'+data.habits.map(h=>'<div class="row"><div class="row-main"><div class="row-title">'+E(h.name)+'</div><div class="row-sub">'+value(h.type,h.today.value)+' / '+value(h.type,h.today.desired)+' · серия '+h.streak+'</div><div class="bar"><i style="width:'+progress(h.today.value,h.today.desired)+'%"></i></div></div>'+(h.type==='timer'?'<button class="play" data-name="'+encodeURIComponent(h.name)+'" title="Начать сессию" aria-label="Начать сессию" onclick="startHabit(this.dataset.name)">'+icons.play+'</button>':'')+'</div>').join('')+'</div>':empty('Нет привычек')}
function mediaGrid(items){return items.length?'<div class="media-grid">'+items.map(m=>'<button class="media" onclick="mediaDetail('+m.id+')" aria-label="'+E(m.title)+'"><div class="cover">'+icons.book+(m.cover&&/^https?:/.test(m.cover)?'<img src="'+E(m.cover)+'" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.hidden=true">':'<span class="cover-label">'+E(labelCollection(m.collection))+'</span>')+'</div><div class="media-body"><span class="tag">'+E(m.status||labelCollection(m.collection))+'</span><div class="media-title">'+E(m.title)+'</div><div class="row-sub">'+E((m.authors||[]).join(', '))+'</div><div class="row-sub">'+m.progress+' / '+(m.total||'—')+' '+E(shortUnit(m.unit))+'</div><div class="bar"><i style="width:'+progress(m.progress,m.total)+'%"></i></div></div></button>').join('')+'</div>':empty('Пока ничего нет')}
function tasks(){return data.tasks.length?'<div class="list">'+data.tasks.map(t=>'<div class="row task"><div><div class="row-title">'+E(t.name)+'</div><div class="row-sub">'+E(t.project)+(t.deadline?' · '+E(t.deadline):'')+'</div></div></div>').join('')+'</div>':empty('Нет срочных задач')}
function view_timer(){if(data.timer){const t=data.timer,action=t.timer_state==='running'?'pause':'resume';return '<section class="section"><div class="timer-hero"><div class="eyebrow"><span class="live-dot"></span>'+(t.timer_state==='running'?'Сессия идёт':'На паузе')+'</div><h2>'+E(t.habit_name)+'</h2>'+(t.media?'<div class="row-sub">'+E(t.media.title)+'</div>':'')+'<div class="timer-dial"><div class="eyebrow">В фокусе</div><div class="timer-clock">'+clock(t.elapsed)+'</div><div class="row-sub">'+(t.target_seconds?'Цель '+clock(t.target_seconds):'Без ограничения')+'</div></div><div class="timer-actions"><button class="secondary" data-action="'+action+'" onclick="timerAction(this.dataset.action)">'+icons[action==='pause'?'pause':'play']+(action==='pause'?'Пауза':'Продолжить')+'</button><button class="primary" onclick="finishTimer()">'+icons.check+'Завершить</button></div></div></section>'}return section('Привычки',data.habits.filter(h=>h.type==='timer').length,habits())+section('Продолжить с произведением',data.current.length,mediaGrid(data.current))}
function view_library(){return '<form class="search" onsubmit="event.preventDefault();search(this.elements.query.value)"><label class="search-field">'+icons.search+'<input name="query" type="search" aria-label="Поиск по библиотеке" value="'+E(filters.q)+'" placeholder="Название или автор"></label><select aria-label="Коллекция" onchange="collection(this.value)"><option value="">Все коллекции</option>'+data.collections.map(c=>'<option value="'+E(c.collection_id)+'" '+(filters.collection===c.collection_id?'selected':'')+'>'+E(labelCollection(c.collection_id))+' ('+c.item_count+')</option>').join('')+'</select></form>'+mediaGrid(data.library)}
function view_stats(){return '<div class="eyebrow">Последние 14 дней</div>'+section('Карта привычек',data.habits.length,'<div class="list">'+data.habits.map(h=>'<div class="stat-card"><div class="stat-top"><strong>'+E(h.name)+'</strong><span>'+h.rate+'%</span></div><div class="heat">'+h.days.map(d=>'<i title="'+E(d.date)+' · '+value(h.type,d.value)+'" class="day '+(d.state==='completed'?'done':d.state==='partial'?'partial':d.state==='missed'?'missed':'')+'"></i>').join('')+'</div><div class="stat-foot"><span>'+E(h.days[0]?.date||'')+'</span><span>'+icons.streak+' Серия: '+h.streak+'</span><span>'+E(h.days.at(-1)?.date||'')+'</span></div></div>').join('')+'</div>')+'<div class="legend"><span><i></i>Выполнено</span><span><i class="partial"></i>Частично</span></div>'}
function empty(t){return'<div class="empty">'+icons.layers+t+'</div>'}function value(type,v){if(type!=='timer')return Math.round(v*10)/10;return Math.round(v/60)+' мин'}
function unit(u){return({pages:'страниц',lessons:'уроков',chapters:'глав',episodes:'эпизодов',minutes:'минут',hours:'часов',items:'произведений',units:'единиц'})[u]||u}function shortUnit(u){return({pages:'стр.',lessons:'ур.',chapters:'гл.',episodes:'эп.',minutes:'мин.',hours:'ч.',items:'шт.'})[u]||u}function labelCollection(c){return({book:'Книги',course:'Курсы',manga:'Манга',film:'Фильмы',anime:'Аниме',series:'Сериалы',game:'Игры'})[c]||c}
function modal(html){document.getElementById('overlay').innerHTML='<div class="modal-wrap" onclick="if(event.target===this)closeModal()"><div class="modal" role="dialog" aria-modal="true" aria-label="Действия"><button class="icon-btn modal-close" aria-label="Закрыть" title="Закрыть" onclick="closeModal()">'+icons.close+'</button>'+html+'</div></div>';document.querySelector('.modal-close')?.focus()}function closeModal(){document.getElementById('overlay').innerHTML=''}document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
function duration(habit,mediaId){modal('<h3>Запустить таймер</h3><div class="row-sub">'+E(habit)+'</div><div class="choices">'+[25,45,60,0].map(m=>'<button class="'+(m===45?'primary':'secondary')+'" data-habit="'+encodeURIComponent(habit)+'" data-media="'+(mediaId||0)+'" data-minutes="'+m+'" onclick="startTimer(this.dataset.habit,Number(this.dataset.media),Number(this.dataset.minutes))">'+(m?m+' минут':'Без ограничения')+'</button>').join('')+'</div>')}
function startHabit(encoded){duration(decodeURIComponent(encoded),0)}function mediaHabit(m){return data.habits.find(h=>h.type==='timer'&&(h.mediaCollections||[]).some(c=>c.toLowerCase()===m.collection.toLowerCase()))}
function startMedia(id){const m=[...data.current,...data.library].find(x=>x.id===id),h=mediaHabit(m);if(!h)return tg?.showAlert('Для коллекции не настроена связанная привычка');duration(h.name,id)}
function mediaDetail(id){const m=[...data.current,...data.library].find(x=>x.id===id);if(!m)return;modal('<span class="tag">'+E(labelCollection(m.collection))+'</span><h3>'+E(m.title)+'</h3><div class="row-sub">'+E((m.authors||[]).join(', '))+'</div><div class="detail-progress">'+m.progress+' / '+(m.total||'—')+' '+E(shortUnit(m.unit))+'</div><div class="bar"><i style="width:'+progress(m.progress,m.total)+'%"></i></div><div class="progress-input"><input id="pv" aria-label="Прогресс" type="number" inputmode="decimal" step="any" placeholder="Количество '+E(unit(m.unit))+'"><button class="secondary" data-mode="add" onclick="saveProgress('+id+',this.dataset.mode)">Добавить</button><button class="secondary" data-mode="exact" onclick="saveProgress('+id+',this.dataset.mode)">Точная позиция</button></div><div class="choices"><button class="primary" onclick="closeModal();startMedia('+id+')">'+icons.play+'Начать сессию</button><button class="secondary" onclick="closeModal()">Закрыть</button></div>')}
async function timerAction(action){await mutate('timer',{action});await load()}async function startTimer(habit,mediaId,minutes){closeModal();await mutate('timer',{action:'start',habit:decodeURIComponent(habit),mediaId:mediaId||undefined,minutes});currentTab='timer';await load()}
async function finishTimer(){try{const r=await api('timer',{method:'POST',body:JSON.stringify({action:'finish'})});await load();if(r.needsProgress&&r.mediaId)mediaDetail(r.mediaId)}catch(e){alertError(e)}}
async function saveProgress(id,mode){const el=document.getElementById('pv'),v=Number(el.value);if(!Number.isFinite(v))return tg?.showAlert('Введите число');await mutate('progress',{id,mode,value:v});closeModal();await load()}
async function mutate(path,body){try{return await api(path,{method:'POST',body:JSON.stringify(body)})}catch(e){alertError(e);throw e}}function alertError(e){tg?.showAlert('Ошибка: '+e.message)}
function search(q){filters.q=q;filters.collection='';load()}function collection(c){filters.collection=c;filters.q='';load()}
${creationScript}
${projectScript}
${sessionScript}
${dailyTaskScript}
const taskOccurrenceDates=${occurrenceDates.toString()};
const occurrenceDates=taskOccurrenceDates;
const shiftDate=${shiftDate.toString()};
const taskCarriesOver=${taskCarriesOver.toString()};
const taskIsOverdue=${taskIsOverdue.toString()};
const taskIsMissed=${taskIsMissed.toString()};
const taskMatches=${taskMatches.toString()};
${taskPlanningScript}
document.querySelector('.title-row').insertAdjacentHTML('beforeend','<button class="icon-btn" onclick="creationMenu()" aria-label="Добавить" title="Добавить">'+icons.plus+'</button>');
const originalLibraryView=view_library;view_library=function(){return '<div class="create-toolbar"><button class="secondary" data-kind="media" onclick="openEntry(this.dataset.kind)">'+icons.plus+'Добавить произведение</button></div>'+originalLibraryView()};
load();
</script></body></html>`;
}
