export const sessionStyle=`
.timer-tabs{display:flex;gap:8px;margin-bottom:20px}.timer-tabs button{flex:1}.history-filters{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-bottom:20px}.history-filters label{min-width:0;color:var(--muted);font-size:12px}.history-filters label:first-child{grid-column:1/-1}.history-filters input,.history-filters select{display:block;width:100%;min-width:0;max-width:100%;padding:10px;margin-top:5px;border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:6px;font:inherit;font-size:14px}
.session-row{display:block;width:100%;border:0;border-bottom:1px solid var(--line);background:none;text-align:left;padding:16px 0;color:var(--text)}.session-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.session-heading strong{min-width:0;overflow-wrap:anywhere}.session-heading b{flex:none;font:500 16px ui-monospace,monospace;color:var(--accent)}.session-result{margin-top:8px;font-size:13px;color:var(--yellow);overflow-wrap:anywhere}.session-detail{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:22px 0}.session-detail small{display:block;color:var(--muted);margin-bottom:5px}.session-note{white-space:pre-wrap;overflow-wrap:anywhere;font-size:14px}.history-totals{display:flex;justify-content:space-between;gap:14px;color:var(--muted);font-size:13px;border-bottom:1px solid var(--line);padding:10px 0}
`;
export const sessionScript=String.raw`
let timerPanel='timer',historyData=null,historyFilters={habit:'',from:'',to:''},historyLoading=false;
const sessionStamp=v=>v?new Date(v).toLocaleString('ru-RU',{timeZone:historyData?.timezone||'Europe/Kyiv',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Не сохранено';
async function loadHistory(more=false){if(historyLoading)return;historyLoading=true;try{const query=new URLSearchParams({...historyFilters,offset:String(more?historyData?.nextOffset||0:0)});const next=await api('sessions?'+query);historyData=more?{...next,items:[...historyData.items,...next.items]}:next;if(currentTab==='timer')render()}catch(e){alertError(e)}finally{historyLoading=false}}
function showTimerPanel(panel){timerPanel=panel;if(currentTab!=='timer')currentTab='timer';render();if(panel==='history')loadHistory()}
function sessionResultText(s){if(s.result)return (s.result.delta>=0?'+':'')+s.result.delta+' '+unit(s.result.unit)+' · '+s.result.progress+'/'+(s.result.total||'—');if(s.status==='cancelled')return 'Отменена · время не начислено';if(s.data.media)return 'Результат чтения или просмотра не указан';if(s.data.task)return 'Время учтено в задаче и привычке';return s.legacy?'Результат отдельно не сохранён':'Время учтено в привычке'}
function historyView(){if(!historyData)return '<div class="loading">Загрузка истории…</div>';return '<div class="history-filters"><label>Привычка<select onchange="historyFilters.habit=this.value;loadHistory()"><option value="">Все привычки</option>'+data.habits.map(h=>'<option value="'+E(h.name)+'" '+(historyFilters.habit===h.name?'selected':'')+'>'+E(h.name)+'</option>').join('')+'</select></label><label>С даты<input type="date" aria-label="С даты" value="'+E(historyFilters.from)+'" onchange="historyFilters.from=this.value;loadHistory()"></label><label>По дату<input type="date" aria-label="По дату" value="'+E(historyFilters.to)+'" onchange="historyFilters.to=this.value;loadHistory()"></label></div><div class="history-totals"><span>'+historyData.totals.count+' сессий</span><span>'+clock(historyData.totals.seconds||0)+' учтено</span></div>'+(historyData.items.length?historyData.items.map(s=>'<button class="session-row" data-id="'+E(s.id)+'" onclick="openSession(this.dataset.id)"><div class="session-heading"><strong>'+E(s.data.task?.name||s.data.media?.title||s.habit_name)+'</strong><b>'+clock(s.duration_sec)+'</b></div><div class="row-sub">'+E(s.habit_name)+' · '+E(s.session_date||'')+'</div><div class="row-sub">'+E(s.started_at?sessionStamp(s.started_at):s.data.startTime||'Начало не сохранено')+' — '+E(s.legacy?s.data.endTime||'Конец не сохранён':sessionStamp(s.ended_at))+'</div><div class="session-result">'+E(sessionResultText(s))+'</div></button>').join(''):empty('За этот период нет сессий'))+(historyData.nextOffset!==null?'<div class="choices"><button class="secondary" onclick="loadHistory(true)">Показать ещё</button></div>':'')}
function openSession(id){const s=historyData?.items.find(s=>s.id===id);if(!s)return;const paused=s.started_at?Math.max(0,Math.floor((s.ended_at-s.started_at)/1000)-s.duration_sec):null;modal('<span class="tag">'+(s.status==='cancelled'?'Отменена':s.legacy?'Ранее сохранённая запись':'Завершена')+'</span><h3>'+E(s.data.task?.name||s.data.media?.title||s.habit_name)+'</h3><div class="row-sub">'+E(s.habit_name)+'</div><div class="session-detail"><div><small>Начало</small>'+E(s.started_at?sessionStamp(s.started_at):s.data.startTime||'Не сохранено')+'</div><div><small>Завершение</small>'+E(s.legacy?s.data.endTime||'Не сохранено':sessionStamp(s.ended_at))+'</div><div><small>В фокусе</small>'+clock(s.duration_sec)+'</div><div><small>Паузы / неучтённое время</small>'+(paused===null?'Не сохранено':clock(paused))+'</div></div><div class="session-result">'+E(sessionResultText(s))+'</div>'+(s.data.note&&s.data.note!=='-'?'<p class="session-note">'+E(s.data.note)+'</p>':'')+(s.result?.note?'<p class="session-note">'+E(s.result.note)+'</p>':'')+(s.data.media&&!s.result&&s.status!=='cancelled'?'<div class="choices"><button class="primary" data-id="'+E(id)+'" onclick="editSessionResult(this.dataset.id)">Указать результат</button></div>':''))}
function editSessionResult(id){const s=historyData?.items.find(s=>s.id===id);if(!s?.data.media)return;const m=s.data.media;modal('<h3>Результат сессии</h3><div class="row-sub">'+E(m.title)+' · '+clock(s.duration_sec)+'</div><form id="session-result-form" class="entry-form" data-id="'+E(id)+'" data-media="'+m.id+'" onsubmit="event.preventDefault();saveSessionResult(this)">'+entrySelect('mode','Прогресс',[['add','Добавить за сессию'],['exact','Точная позиция']])+entryField('value','Количество: '+unit(m.unit),'number','required step="any"')+'<label>Комментарий<textarea name="note" maxlength="2000" rows="3"></textarea></label><div id="session-error" class="entry-error" role="alert"></div><button class="primary" type="submit">'+icons.check+'Сохранить результат</button></form>')}
async function saveSessionResult(form){const button=form.querySelector('[type=submit]');if(button.disabled)return;button.disabled=true;try{await api('progress',{method:'POST',body:JSON.stringify({id:Number(form.dataset.media),sessionId:form.dataset.id,mode:form.elements.mode.value,value:Number(form.elements.value.value),note:form.elements.note.value})});const id=form.dataset.id;closeModal();await loadHistory();openSession(id)}catch(e){document.getElementById('session-error').textContent='Не удалось сохранить результат. '+(e.message==='session_media_mismatch'?'Произведение больше недоступно.':'Повторите попытку.');button.disabled=false}}
finishTimer=function(){modal('<h3>Завершить сессию</h3><form class="entry-form" onsubmit="event.preventDefault();completeSession(this)"><label>Итог или комментарий<textarea name="note" maxlength="2000" rows="3"></textarea></label><div id="session-error" class="entry-error" role="alert"></div><button class="primary" type="submit">'+icons.check+'Сохранить сессию</button></form>')};
async function completeSession(form){const button=form.querySelector('[type=submit]');if(button.disabled)return;button.disabled=true;try{const r=await api('timer',{method:'POST',body:JSON.stringify({action:'finish',note:form.elements.note.value})});closeModal();historyFilters={habit:'',from:'',to:''};await load();await loadHistory();if(r.needsProgress)editSessionResult(r.sessionId);else openSession(r.sessionId)}catch(e){const el=document.getElementById('session-error');if(el)el.textContent='Не удалось завершить сессию. Обновите таймер и проверьте историю.';button.disabled=false}}
const sessionTimerView=view_timer;view_timer=function(){return '<div class="timer-tabs"><button class="'+(timerPanel==='timer'?'primary':'secondary')+'" data-panel="timer" onclick="showTimerPanel(this.dataset.panel)">'+icons.timer+'Таймер</button><button class="'+(timerPanel==='history'?'primary':'secondary')+'" data-panel="history" onclick="showTimerPanel(this.dataset.panel)">'+icons.history+'История</button></div>'+(timerPanel==='history'?historyView():sessionTimerView())};
const sessionLoad=load;load=async function(){await sessionLoad();if(currentTab==='timer'&&timerPanel==='history')await loadHistory()};
const sessionStart=startTimer;startTimer=async function(...args){timerPanel='timer';return sessionStart(...args)};
const sessionProjectStart=startBoardTask;startBoardTask=async function(...args){timerPanel='timer';return sessionProjectStart(...args)};
`;
