export const projectStyle=`
.nav{grid-template-columns:repeat(5,minmax(0,1fr))}.board-toolbar{display:flex;gap:10px;margin-bottom:18px;align-items:center}.board-toolbar select{min-width:0;flex:1;padding:12px;background:var(--panel);color:var(--text);border:1px solid var(--line);border-radius:6px;font:inherit}
.kanban{display:flex;gap:14px;overflow-x:auto;padding-bottom:18px;scroll-snap-type:x proximity;align-items:flex-start}.kanban-column{flex:0 0 260px;min-width:0;scroll-snap-align:start}.kanban-column h2{display:flex;justify-content:space-between;font-size:14px;margin:0;padding:12px 0;border-top:3px solid var(--accent)}.kanban-column:nth-child(2n) h2{border-color:var(--yellow)}.kanban-column:nth-child(3n) h2{border-color:var(--coral)}
.task-card{background:var(--panel);border:1px solid var(--line);border-radius:7px;margin:10px 0;padding:13px}.task-card>button.task-title{display:block;width:100%;text-align:left;border:0;background:none;padding:0;font-weight:600;font-size:14px;overflow-wrap:anywhere}.task-card .row-sub{margin:8px 0}.task-footer{display:flex;align-items:center;justify-content:space-between;gap:8px}.task-footer select{min-width:0;width:100%;background:var(--bg);color:var(--text);border:1px solid var(--line);border-radius:5px;padding:7px;font:inherit;font-size:12px}.task-footer .icon-btn{width:34px;height:34px}.task-due.overdue{color:var(--coral)}
.subtask-edit{display:grid;grid-template-columns:22px minmax(0,1fr) 34px;gap:8px;align-items:center;margin-bottom:8px}.entry-form .subtask-edit input[type=checkbox]{width:20px;height:20px;accent-color:var(--accent)}.subtask-edit .icon-btn{width:32px;height:32px}.danger{color:var(--coral);border-color:var(--coral)}.project-empty{padding:25px 0;color:var(--muted);font-size:13px}
`;
export const projectScript=String.raw`
let board=null,boardScope='',boardBusy=false;
async function loadBoard(){try{board=await api('projects');if(!board.scopes.some(s=>s.id===boardScope))boardScope=board.scopes[0]?.id||'';if(currentTab==='projects')render()}catch(e){alertError(e)}}
function view_projects(){if(!board)return '<div class="loading">Загрузка проектов…</div>';if(!board.scopes.length)return empty('Проекты ещё не синхронизированы из Obsidian');const scope=board.scopes.find(s=>s.id===boardScope),columns=scope.statuses.split(',').map(s=>s.trim()).filter(Boolean),items=board.tasks.filter(t=>t.scopeId===scope.id);const extras=[...new Set(items.map(t=>t.status).filter(s=>!columns.includes(s)))];return '<div class="board-toolbar"><select aria-label="Проект" onchange="boardScope=this.value;render()">'+board.scopes.map(s=>'<option value="'+E(s.id)+'" '+(s.id===boardScope?'selected':'')+'>'+E(s.name)+'</option>').join('')+'</select><button class="primary" onclick="editBoardTask()">'+icons.plus+'Задача</button></div><div class="kanban">'+[...columns,...extras].map(status=>'<section class="kanban-column" data-status="'+E(status)+'" ondragover="event.preventDefault()" ondrop="dropBoardTask(event,this.dataset.status)"><h2>'+E(status)+'<span class="count">'+items.filter(t=>t.status===status).length+'</span></h2>'+items.filter(t=>t.status===status).map(t=>boardCard(t,columns)).join('')+'</section>').join('')+'</div>'}
function boardCard(t,columns){const key=E(t.key),done=t.subtasks.filter(s=>s.checked).length;return '<article class="task-card" draggable="true" data-key="'+key+'" ondragstart="event.dataTransfer.setData(\'text/plain\',this.dataset.key)"><button class="task-title" data-key="'+key+'" onclick="editBoardTask(this.dataset.key)">'+E(t.name)+'</button><div class="row-sub">'+E(({high:'Высокий',medium:'Средний',low:'Низкий'})[t.priority]||'Без приоритета')+(t.endDate?' · <span class="task-due '+(t.endDate<data.date?'overdue':'')+'">'+E(t.endDate)+'</span>':'')+'</div><div class="row-sub">'+(t.subtasks.length?done+'/'+t.subtasks.length+' подзадач · ':'')+clock(t.timeSpentSec)+(t.pending?' · Ожидает Obsidian':'')+'</div><div class="task-footer"><select aria-label="Статус задачи" data-key="'+key+'" onchange="moveBoardTask(this.dataset.key,this.value)">'+[...new Set([...columns,t.status])].map(s=>'<option '+(s===t.status?'selected':'')+'>'+E(s)+'</option>').join('')+'</select><button class="icon-btn" data-key="'+key+'" onclick="startBoardTask(this.dataset.key)" aria-label="Таймер задачи" title="Таймер задачи">'+icons.play+'</button></div></article>'}
function subtaskRow(s={text:'',checked:false}){return '<div class="subtask-edit"><input type="checkbox" aria-label="Подзадача выполнена" '+(s.checked?'checked':'')+'><input type="text" aria-label="Название подзадачи" maxlength="250" value="'+E(s.text)+'"><button type="button" class="icon-btn" title="Убрать подзадачу" aria-label="Убрать подзадачу" onclick="this.parentElement.remove()">'+icons.close+'</button></div>'}
function editBoardTask(key){const task=board.tasks.find(t=>t.key===key),scope=board.scopes.find(s=>s.id===(task?.scopeId||boardScope));if(!scope)return;const columns=scope.statuses.split(',').map(s=>s.trim()).filter(Boolean);const defaults=task||{name:'',status:columns[0],priority:'',habitName:'',startDate:'',endDate:'',timeEstimatedSec:0,subtasks:[]};modal('<h3>'+(task?'Задача':'Новая задача')+'</h3><form id="board-form" class="entry-form" onsubmit="event.preventDefault();saveBoardForm(this)">'+entryField('name','Название','text','required maxlength="250"')+'<div class="entry-pair">'+entrySelect('status','Статус',columns.map(s=>[s,s]))+entrySelect('priority','Приоритет',[['','Без приоритета'],['high','Высокий'],['medium','Средний'],['low','Низкий']])+'</div><div class="entry-pair">'+entryField('startDate','Начало','date')+entryField('endDate','Дедлайн','date')+'</div>'+entrySelect('habitName','Связанная привычка',[['','Не выбрана'],...data.habits.filter(h=>h.type==='timer').map(h=>[h.name,h.name])])+entryField('estimate','Оценка времени, минут','number','min="0" max="525600" step="any"')+'<div><label>Подзадачи</label><div id="board-subtasks">'+defaults.subtasks.map(subtaskRow).join('')+'</div><button class="secondary" type="button" onclick="document.getElementById(\'board-subtasks\').insertAdjacentHTML(\'beforeend\',subtaskRow())">'+icons.plus+'Подзадача</button></div><div id="board-error" class="entry-error" role="alert"></div><button type="submit" class="primary">'+icons.check+'Сохранить</button>'+(task?'<button type="button" class="secondary danger" onclick="confirmBoardDelete()">'+icons.trash+'Удалить задачу</button>':'')+'</form>');const f=document.getElementById('board-form');f.dataset.key=key||'';f.dataset.revision=task?.revision??0;f.dataset.request=crypto.randomUUID();for(const name of ['name','status','priority','habitName','startDate','endDate'])f.elements[name].value=defaults[name];f.elements.estimate.value=defaults.timeEstimatedSec?defaults.timeEstimatedSec/60:'';f.elements.name.focus()}
function boardError(e){return ({task_conflict:'Задача уже изменилась. Закройте форму и обновите доску.',task_duplicate:'Задача с таким названием уже существует.',task_habit_required:'Выберите связанную привычку в редакторе задачи.',invalid_task:'Проверьте название, даты и подзадачи.',task_timer_running:'Сначала завершите таймер этой задачи.',timer_exists:'Другой таймер уже запущен.'})[e.message]||'Не удалось сохранить изменения. Повторите попытку.'}
async function saveBoardForm(form){if(boardBusy||!form.reportValidity())return;boardBusy=true;const button=form.querySelector('[type=submit]');button.disabled=true;const task=Object.fromEntries(new FormData(form));task.scopeId=boardScope;task.timeEstimatedSec=Number(task.estimate||0)*60;task.subtasks=[...document.querySelectorAll('#board-subtasks .subtask-edit')].map(el=>({text:el.querySelector('[type=text]').value.trim(),checked:el.querySelector('[type=checkbox]').checked})).filter(s=>s.text);try{await api('projects',{method:'POST',body:JSON.stringify({action:form.dataset.key?'save':'create',key:form.dataset.key,revision:Number(form.dataset.revision),requestId:form.dataset.request,task})});closeModal();await loadBoard()}catch(e){document.getElementById('board-error').textContent=boardError(e)}finally{boardBusy=false;button.disabled=false}}
function confirmBoardDelete(){const form=document.getElementById('board-form'),key=form.dataset.key,revision=Number(form.dataset.revision),task=board.tasks.find(t=>t.key===key);modal('<h3>Удалить задачу?</h3><p>'+E(task.name)+'</p><p class="row-sub">Подзадачи также будут удалены. Изменение передастся в Obsidian.</p><div id="board-error" class="entry-error"></div><div class="choices"><button class="secondary" data-key="'+E(key)+'" onclick="editBoardTask(this.dataset.key)">Отмена</button><button class="secondary danger" data-key="'+E(key)+'" data-revision="'+revision+'" data-request="'+crypto.randomUUID()+'" onclick="deleteBoardTask(this)">'+icons.trash+'Удалить</button></div>')}
async function deleteBoardTask(button){if(boardBusy)return;boardBusy=true;button.disabled=true;try{await api('projects',{method:'POST',body:JSON.stringify({action:'delete',key:button.dataset.key,revision:Number(button.dataset.revision),requestId:button.dataset.request,confirm:true})});closeModal();await loadBoard()}catch(e){document.getElementById('board-error').textContent=boardError(e)}finally{boardBusy=false;button.disabled=false}}
async function moveBoardTask(key,status){if(boardBusy)return;const task=board.tasks.find(t=>t.key===key);if(!task||task.status===status)return;boardBusy=true;try{await api('projects',{method:'POST',body:JSON.stringify({action:'save',key,revision:task.revision,requestId:crypto.randomUUID(),task:{...task,status}})});await loadBoard()}catch(e){tg?.showAlert(boardError(e));await loadBoard()}finally{boardBusy=false}}
function dropBoardTask(event,status){event.preventDefault();moveBoardTask(event.dataTransfer.getData('text/plain'),status)}
async function startBoardTask(key){try{await api('projects',{method:'POST',body:JSON.stringify({action:'start',key})});currentTab='timer';await load()}catch(e){if(e.message==='task_habit_required')editBoardTask(key);else alertError(e)}}
const baseRender=render;render=function(){baseRender();if(currentTab==='projects')document.getElementById('heading').textContent='Проекты'};
const baseTab=tab;tab=function(name){baseTab(name);if(name==='projects')loadBoard()};
const baseLoad=load;load=async function(){await baseLoad();if(currentTab==='projects')await loadBoard()};
const baseTimerView=view_timer;view_timer=function(){let task=null;try{task=JSON.parse(data.timer?.task_json||'null')}catch{}return (task?'<div class="section-head"><h2>'+E(task.name)+'</h2></div>':'')+baseTimerView()};
document.querySelector('.nav').insertAdjacentHTML('beforeend','<button data-tab="projects" onclick="tab(this.dataset.tab)">'+icons.kanban+'Проекты</button>');
`;
